"""initial_schema

Revision ID: 20c538b930fc
Revises: 1942f2a63fe8
Create Date: 2026-03-19 03:05:42.047768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c538b930fc'
down_revision: Union[str, Sequence[str], None] = '1942f2a63fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_alerts_claimed_by_users', 'users', ['claimed_by'], ['id'])
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('assigned_to')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_clip_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('audio_clip_path', sa.String(length=500), nullable=True))
        batch_op.drop_column('audio_url')
        batch_op.drop_column('video_url')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_health_check')

    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('audio_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('audio_clip_path')
        batch_op.drop_column('video_clip_path')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.CHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claimed_by')

    # ### end Alembic commands ###
