"""add hall_id and monitoring fields to assignment

Revision ID: c3a2ebcd87b1
Revises: ce3587b4e14d
Create Date: 2026-05-15 11:42:59.992664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a2ebcd87b1'
down_revision: Union[str, Sequence[str], None] = 'ce3587b4e14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hall_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('monitoring_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('monitoring_ended_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_assignments_hall_id_halls', 'halls', ['hall_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('stream_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('stream_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assignments_hall_id_halls', type_='foreignkey')
        batch_op.drop_column('monitoring_ended_at')
        batch_op.drop_column('monitoring_started_at')
        batch_op.drop_column('hall_id')

    # ### end Alembic commands ###
